### ISSUE TITLE
There are some problems with the accuracy of the model

### ISSUE THREAD

**Issue by Trent-tangtao** [D-X-Y/NATS-Bench#11]
**Which Algorithm**
Size Search Space
Cifar 10

**Describe the Question**
I get all 32768 architecture candidates‘ acc using the code followed, but all of them in under 90%.
The results in your paper of all method is above 90%. How can I get the result of table 4 in your paper?

from nats_bench import create
model_cifar10_rank = {}
api = create(None, 'sss')
for index in range(32768):
    info = api.get_more_info(index, 'cifar10')
    config = api.get_net_config(index, 'cifar10')
    model_cifar10_rank[config['channels']] = info['test-accuracy']

[models_cifar10_acc_rank 2.txt](https://github.com/D-X-Y/AutoDL-Projects/files/6106710/models_cifar10_acc_rank.2.txt)

**Comment by D-X-Y** [comment]
@Littleyezi `hp=12` is used during searching to obtain the validation accuracy. `hp=200` is used to report the final performance of the searched architecture.
After search, it is not suggested to call `simulate_train_eval`.
