### ISSUE TITLE
Do models trained with same dataset eg. CIFAR10, use SAME SEED?

### ISSUE THREAD

**Issue by dercaft** [D-X-Y/NATS-Bench#14]
**Describe the Question**
Hello Dr. Dong:
Do models trained with same dataset eg. CIFAR10, use same seed?

**Comment by D-X-Y** [comment]
For most models, yes.

**Comment by dercaft** [comment]
Thanks, I find api contains argument which offer selection of random seed.
```python
api_tss = create(path, 'tss', fast_mode=True, verbose=False)
info=api_tss.get_more_info(index,data,hp=hp,iepoch=epoch,is_random=seed)
```
