### ISSUE TITLE
The unit for the number of parameters

### ISSUE THREAD

**Issue by paul-ang** [D-X-Y/NATS-Bench#16]
Hi,

Thanks very much for your work.

Regarding the number of parameters for each network architecture, what is the unit (e.g. million)?

Thank you.

<img width="367" alt="Screen Shot 2021-05-26 at 2 38 42 pm" src="https://user-images.githubusercontent.com/17742813/119603213-1a119680-be30-11eb-91dc-c7cfb1f88302.png">

**Comment by D-X-Y** [comment]
Yes. To be more specific, it is calculated by calling [this function](https://github.com/D-X-Y/AutoDL-Projects/blob/main/xautodl/utils/flop_benchmark.py#L9)
