### ISSUE TITLE
'tss' node connection?

### ISSUE THREAD

**Issue by LicharYuan** [D-X-Y/NATS-Bench#18]
**Describe the Question**
A clear and concise description of the question.
- Is it about the topology search space in NATS-Bench? Yes
- Is it about the size search space in NATS-Bench? No
- Which figure or table are you referring to in the paper? Not Found.

Hi, after create bench API, query the relative information as followed:

```python
In [7]: tss.query_info_str_by_arch(1)
[2021-06-23 08:09:56] Call query_info_str_by_arch with arch=1and hp=12
[2021-06-23 08:09:56] Call query_index_by_arch with arch=1
[2021-06-23 08:09:56] Call clear_params with archive_root=../NATS-tss-v1_0-3ffb9-simple and index=1
Out[7]: "|nor_conv_3x3~0|+|nor_conv_3x3~0|avg_pool_3x3~1|+|skip_connect~0|nor_conv_3x3~1|skip_connect~2|\ndatasets : ['cifar10-valid', 'cifar10', 'cifar100', 'ImageNet16-120'], extra-info : arch-index=1\ncifar10-valid  FLOP=113.95 M, Params=0.802 MB, latency=16.85 ms.\ncifar10-valid  train : [loss = 0.382 & top1 = 86.97%], valid : [loss = 0.514 & top1 = 82.83%]\ncifar10        FLOP=113.95 M, Params=0.802 MB, latency=16.85 ms.\ncifar10        train : [loss = 0.243 & top1 = 91.69%], test  : [loss = 0.362 & top1 = 88.22%]\ncifar100       FLOP=113.96 M, Params=0.808 MB, latency=15.36 ms.\ncifar100       train : [loss = 1.271 & top1 = 63.76%], valid : [loss = 1.495 & top1 = 57.80%], test : [loss = 1.478 & top1 = 58.26%]\nImageNet16-120 FLOP= 28.50 M, Params=0.810 MB, latency=13.77 ms.\nImageNet16-120 train : [loss = 2.548 & top1 = 35.41%], valid : [loss = 2.580 & top1 = 35.43%], test : [loss = 2.611 & top1 = 33.80%]"`
```

what the `nor_` means? and which one presents the connection between node0 and node1?

**Comment by D-X-Y** [comment]
Thanks for your questions. `nor_conv_3x3` indicates a 3-by-3 convolution, the connection between node-0 and node-1 is implicitly shown in this string. 
Specifically, `|nor_conv_3x3~0|+|nor_conv_3x3~0|avg_pool_3x3~1|+|skip_connect~0|nor_conv_3x3~1|skip_connect~2|` indicates the topology of a cell with three nodes: `|nor_conv_3x3~0|` and `|nor_conv_3x3~0|avg_pool_3x3~1|` and `|skip_connect~0|nor_conv_3x3~1|skip_connect~2|`.
- `|nor_conv_3x3~0|` means the tensor of node-1 is 3-by-3-conv( input of this cell (indicated as 0) )
- `|nor_conv_3x3~0|avg_pool_3x3~1|` means the tensor of node-2 is `3-by-3-conv( input of this cell )` plus `pool( node-1 )`.

**Comment by LicharYuan** [comment]
I see. Thanks for the reply!

**Comment by D-X-Y** [comment]
U are welcome~
