### ISSUE TITLE
About getting the size in Bytes of the possible candidates

### ISSUE THREAD

**Issue by brunogriep** [D-X-Y/NATS-Bench#21]
I'm having some issues to use one of those candidates of the Size Search Space when it comes to measure the size in bytes of a specific candidate.
I know to do it using the tensorflow lite kit, but I don't have any idea how to get the model to a `torch.nn` object and measure it.

**Comment by D-X-Y** [comment]
Thanks for your interest in our NATS-Bench.
I have created an example for you, on how to measure the byte size of a candidate at [here](https://github.com/D-X-Y/NATS-Bench/blob/main/notebooks/issue-21.ipynb). Please let me know if you have other questions.

**Comment by brunogriep** [comment]
Thank you so much for your support. This example of yours, was exactly what I needed.
