### ISSUE TITLE
get_model_from_arch_str

### ISSUE THREAD

**Issue by guochengqian** [D-X-Y/NATS-Bench#22]
**Describe the Question**
is there a function for getting the model instance from the cell string? this function will be very useful for nas with training method?

**Comment by D-X-Y** [comment]
Yes, we do have.
Please see README at [here](https://github.com/D-X-Y/NATS-Bench#3-create-the-instance-of-an-architecture-candidate-in-nats-bench)

**Comment by guochengqian** [comment]
wow. thank you!
