### ISSUE TITLE
Some Baidu-Pan links are invalid now.

### ISSUE THREAD

**Issue by ShunLu91** [D-X-Y/NATS-Bench#23]
**Describe the Question**
Great thanks for your nice work!

- Is it about the topology search space in NATS-Bench?
- Yes
- Is it about the size search space in NATS-Bench?
- No
- Which figure or table are you referring to in the paper?
- Especially the download link of NATS-tss-v1_0-3ffb9-full is invalid. Could you please update this link?

Best regards.

**Comment by D-X-Y** [comment]
Thanks for pointing out the issue. I have updated the invalid link.
Please have a try and let me know if there is still an issue.

**Comment by ShunLu91** [comment]
Hi, thanks very very much for your such quick reply! 👍 👍 👍
I have save all the files according to your updated Baidu links.
I will continue to pay attention to this work and help to share the valid links to others in this page if the Baidu links become invalid again.
Great thanks and best wishes!

**Comment by D-X-Y** [comment]
Cool, glad to know it works and thanks for your kindness :)
