### ISSUE TITLE
FLOPS data in nasbench201 are different from flops count tools like thop and ptflops

### ISSUE THREAD

**Issue by AlbertiPot** [D-X-Y/NATS-Bench#24]
**FLOPS counts**
- about the topology search space in NATS-Bench?

Hi, the question is that when I using the flops counts tools to calculate the flops of the model in nasbench201, the results are always larger than the flops offered by 201 dataset, for example arch index 0, cifar10-valid flops 15.64737, cifar100 15.65322, and imagenet16 flops 3.91948, however from the thop tools they are 16.464576, 16.470336, 4.123712, from the ptflops tools they are 16.810634, 16.816484, 4.210296. But either 201 dataset or the above tools offer the same params counts.

are there any operations that the model does not count? 

Many thanks for your excellent works and code！

**Comment by AlbertiPot** [comment]
code here for building network and using thop to count the flops
`from xautodl.models import get_cell_based_tiny_net

index = 0
cifar10_config = api.get_net_config(index,'cifar10-valid')
print(cifar10_config)
cifar10_network = get_cell_based_tiny_net(cifar10_config)

from thop import profile
import torch

input = torch.randn(1,3,32,32)
flops, params = profile(cifar10_network, inputs={input,})
print(flops/1e6, params/1e6)`

**Comment by D-X-Y** [comment]
And, personally, I do not know either thop or my codes are calculating the precise FLOPs. If you want the best FLOPs numbers, I would recommend https://github.com/facebookresearch/fvcore#features from Facebook.
Unfortunately, I did not realize this tool when I build the benchmark.
