### ISSUE TITLE
Why is 1GB file can destroy my 12GB colab RAM?

### ISSUE THREAD

**Issue by huynhnhathao** [D-X-Y/NATS-Bench#25]
Why is the benchmark tss file is only 1G, but when I create api with fast_mode = False, it causes my notebook to crash because of out of memory?

**Comment by huynhnhathao** [comment]
I have tried what you said, however when I loop over the whole dataset it takes too long. For example, my function below would take almost 2 hours on google colab to run. Is that normal or it's just me?
```
def extract_data(api, dataset):
    # extract flops and test acc for dataset for all architectures
    data = np.zeros(shape = (len(api), 2))
    for i in trange(len(api)):
        flops = api.get_cost_info(i, dataset)['flops']
        test_error = 100 - api.get_more_info(i, dataset, hp = 200)['test-accuracy']
        data[i, 0], data[i, 1] = test_error, flops
    return data
```
By the way, did you mean `create(None, 'tss', fast_mode=True)` when using the archive tss?

**Comment by D-X-Y** [comment]
Yes,, if you traverse all candidates, then the memory cost will be the same and due to the online nature, it will also be slower..
You may need a better machine to run the function. I tried on my personal mac for these functions, which are be completed by < 10 mins

**Comment by huynhnhathao** [comment]
Ok, thank you for answering my questions.
