### ISSUE TITLE
Loading the pre-trained weights

### ISSUE THREAD

**Issue by Mshz2** [D-X-Y/NATS-Bench#28]
Hi, I have got the network instance by running:
`api = create('/path/to/NATS-sss-v1_0-50262-simple', 'sss', fast_mode=True, verbose=True)`
`config = api.get_net_config(12, 'cifar10')`
`network = get_cell_based_tiny_net(config)`

everything works until here, but when I want to load the pretrained weights on the network like below:

`params = api.get_net_param(12, 'cifar10', None)`
`network.load_state_dict(next(iter(params.values())))`
I get the error below:

> ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_23823/187443033.py in <module>
----> 1 network.load_state_dict(next(iter(params.values())))

/anaconda/envs/py38_pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
   1377         # copy state_dict so _load_from_state_dict can modify it
   1378         metadata = getattr(state_dict, '_metadata', None)
-> 1379         state_dict = state_dict.copy()
   1380         if metadata is not None:
   1381             # mypy isn't aware that "_metadata" exists in state_dict

AttributeError: 'NoneType' object has no attribute 'copy'

**_Can you please help me how can I have a pretrained network?_**

**Comment by D-X-Y** [comment]
It was because you are loading the benchmark folder `NATS-sss-v1_0-50262-simple` instead of `NATS-sss-v1_0-50262-full`. The `NATS-sss-v1_0-50262-simple` does not contain the pre-trained weights as they are too large. If you want to load the pre-trained weights, please download `NATS-sss-v1_0-50262-full` and feed into the `create` function~
