### ISSUE TITLE
Size of a network instance is so small, after being trained

### ISSUE THREAD

**Issue by Mshz2** [D-X-Y/NATS-Bench#29]
Hi, I have sampled an architecture by `network = get_cell_based_tiny_net(config)`, and then simply trained it and then saving the whole architecture object with `torch.save(network, fname)`. 
**When I check the size of a network, it is _only 1.15 MB_. Is it normal that I get so much lightweight network?**
Best

**Comment by D-X-Y** [comment]
Can you print the config?

**Comment by Mshz2** [comment]
> Can you print the config?

{'name': 'infer.shape.tiny', 'channels': '16:40:56:24:40', 'genotype': '|nor_conv_3x3~0|+|nor_conv_3x3~0|nor_conv_3x3~1|+|skip_connect~0|nor_conv_3x3~1|nor_conv_3x3~2|', 'num_classes': 10}

**Comment by D-X-Y** [comment]
Gotcha.
It is normal that most candidates in NATS-Bench are "lightweight" models. You can check Figure 3 in our paper.
