### ISSUE TITLE
Different number of training epochs

### ISSUE THREAD

**Issue by debadeepta** [D-X-Y/NATS-Bench#3]
**Each architecture is trained for 12 (H^0), 200 (H^1), and 90 (H^2) epochs. If only these two epoch numbers are used, what does it mean to report test accuracies at all epochs of training 'ori-test@0', 'ori-test@1', 'ori-test@2'......'ori-test@199'. Shouldn't there be just ori-test@12 and ori-test@199?  
**

**Comment by D-X-Y** [comment]
'ori-test@0', 'ori-test@1', ..., 'ori-test@198', 'ori-test@199' indicate the accuracy after 1 or 2 or ... or 199 or 200 epochs when the total training epochs are 200.
