### ISSUE TITLE
ValueError: can not find random seed (999) from [777, 888]

### ISSUE THREAD

**Issue by nabenabe0928** [D-X-Y/NATS-Bench#30]
As the title mentions, I got the error by the following code:
```
import os
import nats_bench

DATA_DIR = f"{os.environ['HOME']}/research/data/NATS-tss-v1_0-3ffb9-simple"
name = 'ImageNet16-120'
data = nats_bench.create(DATA_DIR, 'tss', fast_mode=True, verbose=False)

data.get_more_info(index=346, dataset=name, hp='200', iepoch=199, is_random=999)
>>> No error

data.get_more_info(index=347, dataset=name, hp='200', iepoch=199, is_random=999)
>>> ValueError
```

The trained data of seed 999 for some architectures are not available?
Or am I doing something wrong?

**Comment by D-X-Y** [comment]
Yes, some architectures do not have all three seeds in the `tss` search space. I will upgrade the benchmark to show more useful error message.

**Comment by nabenabe0928** [comment]
Thanks for the quick response.
It helps me a lot.
