### ISSUE TITLE
About REINFORCE

### ISSUE THREAD

**Issue by tjdeng** [D-X-Y/NATS-Bench#32]
你好! 
我对 AutoDL-Projects-main/exps/NATS-algos/reinforce.py 中policy的实现有些疑惑，我理解基于RL策略的NAS算法中agent的架构一般是RNN，但这里 PolicyTopology  的网络架构并不是RNN（我没太理解这个网络架构所蕴含的含义，只知道参数的大小[6边, 5动作候选集]），且forward没有输入．那么请问这里对 REINFORCE 的实现机理是什么呢？

**Comment by D-X-Y** [comment]
这里的 PolicyTopology 和 RNN 类似。在NAS算法中，RNN agent一般也是没有原始input的。
