### ISSUE TITLE
api.simulate_train_eval throws error when passing in cifar100 dataset with fixed epoch

### ISSUE THREAD

**Issue by MinhTuDo** [D-X-Y/NATS-Bench#33]
**Describe the bug**
I get KeyError: 'valid-accuracy' when using api.simulate_train_eval for cifar100 dataset and predefined iepoch parameter
**To Reproduce**
```
api = create(None, 'tss', fast_mode=True, verbose=False)
api.simulate_train_eval(1, 'cifar100', iepoch=24, hp='200')
```

I'm using Ubuntu-21.10. Python 3.8.12, Pytorch 1.8.1

**Comment by D-X-Y** [comment]
Thanks for pointing out this issue, I will look at this today~

**Comment by D-X-Y** [comment]
Thanks for your patience, I just upgraded the NATS-Bench to `v1.5`, in which this bug has been fixed.
Please use `pip install nats-bench==1.5` to install our up-to-date version of NATS-Bench~

**Comment by D-X-Y** [comment]
An example notebook is at https://github.com/D-X-Y/NATS-Bench/blob/main/notebooks/issue-33.ipynb
