### ISSUE TITLE
The reasults of test accuracy

### ISSUE THREAD

**Issue by tjdeng** [D-X-Y/NATS-Bench#35]
**Describe the Question**
A clear and concise description of the question.
- topology search space in NATS-Bench

Hi, I am confused by how to query one arch's test accuracy correctly. I did a test about querying one arch in two different ways. here are the code and outputs:
```python
from nats_bench import create

search_space = 'tss'

api = create(None, search_space, fast_mode=True, verbose=True)

print(50 * '-')
info = api.get_more_info(
            1,
            dataset = "cifar10-valid",
            hp="200" if search_space == "tss" else "90",
            # hp='12',
            is_random=False
        )
print(info)

print(50 * '-')

info = api.query_info_str_by_arch(
    1, "200" if search_space == "tss" else "90"
)
print(info)
```
![1641286810(1)](https://user-images.githubusercontent.com/49608703/148034976-e8aad911-1f0b-451f-b504-9f42a08c1fef.png)

As the picture shows, the same arch gets different test accuracy. So what is the difference between these two ways? and which one you used in your paper.

**Comment by D-X-Y** [comment]
cifar10-valid and cifar10 are a bit tricky.
If you try:
```
info = api.get_more_info(
            1,
            dataset = "cifar10",  # not cifar10-valid
            hp="200" if search_space == "tss" else "90",
            # hp='12',
            is_random=False
        )
print(info)
```
Then the test accuracy is the same as what you got from `api.query_info_str_by_arch`.

**Comment by tjdeng** [comment]
I got it. Thank you for your reply.
