### ISSUE TITLE
Problem recreating api in fastmode

### ISSUE THREAD

**Issue by jahdkaran** [D-X-Y/NATS-Bench#37]
Hey,
I use the tss api with the simple dataset and it works fine first time, but when i try to recreate the api from the path that the simple dataset is placed in i encounter an error telling me that the meta.pickle.bz was not found. the solution is to unarchive the tar file everytime.
Am I missing sth?
Thanks in advance

**Comment by D-X-Y** [comment]
Hi @jahdkaran 
Would you mind writing a code snapshot, either a python file or a notebook is fine? so that I can try to reproduce the issue that you met?

Best regards.
Xuanyi

**Comment by D-X-Y** [comment]
Temporarily close this issue due to missing follow-up
