### ISSUE TITLE
Training time per epoch reproduction

### ISSUE THREAD

**Issue by debadeepta** [D-X-Y/NATS-Bench#4]
**I am trying to reproduce the training pipeline for architectures in tss. For example architecture index 284 shows training per epoch time of 9.75 seconds but in my code where I am keeping the hyperparameters same as in Table 2 in the paper, I am getting around 50 seconds per epoch on a 2080Ti gpu. There are probably minor differences in the trianing pipeline but wondering if I am missing a big detail somewhere. **

**Comment by D-X-Y** [comment]
The training time is quite different between different environments, due to type of GPU, #CPUs, etc. It might be possible that we are getting different time.
Note that the time provided in NATS-Bench is obtained on the same machine and environment~

**Comment by debadeepta** [comment]
Makes sense! What was the GPU/CPU used for natsbench?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by D-X-Y** [comment]
For architecture in tss, we use P100. For architectures in sss, we use V100. For all exps, we use 4 CPUs, the normal one on GCP.
