### ISSUE TITLE
The code for ImageNet16 is 404 error

### ISSUE THREAD

**Issue by yaolu-zjut** [D-X-Y/NATS-Bench#41]
**The code for ImageNet16 is 404 error**
would you please a new link or new codes for me to load ImageNet16

**Comment by D-X-Y** [comment]
Sure, just updated!

**Comment by D-X-Y** [comment]
If you need to use the pre-trained weights, you need to download all `NATS-tss-v1_0-3ffb9-full.tara*` and merge them via `cat NATS-tss-v1_0-3ffb9-full.tara* > NATS-tss-v1_0-3ffb9-full.tara`. (which is mentioned in step-2 in https://github.com/D-X-Y/NATS-Bench#preparation-and-download).
You can not use `NATS-tss-v1_0-3ffb9-full.taraa` as it is just a piece of the whole zip file..

**Comment by yaolu-zjut** [comment]
Thank you, I will try it again.
