### ISSUE TITLE
api_utils.py invoking get_latency method without passing "hp" parameter

### ISSUE THREAD

**Issue by rtu715** [D-X-Y/NATS-Bench#44]
https://github.com/D-X-Y/NATS-Bench/blob/d1fcb7ab8679c8231e1aaf1fc08f94449c88e8d6/nats_bench/api_utils.py#L273

Could you please do this one-line fix? Now it defaults to passing in 200 as "hp" without allowing for other values.

**Comment by D-X-Y** [comment]
Hi Renbo, thanks for pointing out this bug. I just pushed the fix in the main branch and will push it to pip soon

**Comment by D-X-Y** [comment]
FYI, it has just been pushed to `pypi`: https://pypi.org/project/nats-bench/.

**Comment by rtu715** [comment]
Thanks a lot!
