### ISSUE TITLE
No testset in ImageNet16

### ISSUE THREAD

**Issue by nukeyyou** [D-X-Y/NATS-Bench#45]
There is no specified **test set** in the Google Drive sharings. 
I am not sure which part of data should be used when testing the models' accuracy.

**Comment by D-X-Y** [comment]
Please refer to codes at https://github.com/D-X-Y/AutoDL-Projects/blob/main/xautodl/datasets/get_dataset_with_transform.py#L222-L226

**Comment by nukeyyou** [comment]
Sorry. I found the loading method in the readme but I dont know how to delete this question so I set it closed.
BTW, I want to ask if the clear_params function is designed to saving memory cuz I am facing a memory leaking problem. My PC take like 9hrs to run 1 traversal but always got process killed in half-way. It's hard for debugging.
