### ISSUE TITLE
get_net_param returns empty dictionary

### ISSUE THREAD

**Issue by fracapuano** [D-X-Y/NATS-Bench#49]
**Describe the bug**
When retrieving network parameters with `get_net_param` I obtain an empty dict that I clearly cannot import as state_dict of a Pytorch model.

**To Reproduce**
Please provide a small script to reproduce the behavior:
```python
from nats_bench import create
nats_api = create("NATS-tss-v1_0-3ffb9-simple", search_space="topology", fast_mode=True, verbose=False)
# sample random idx to simulate behavior
random_idx = nats_api.random()
# get corresponding architecture on CIFAR10
random_architecture = nats_api.get_net_config(index=random_idx, dataset="cifar10")
# retrieve network parameters according to main README.md
random_params = nats_api.get_net_param(index=random_idx, dataset="cifar10", seed=None)
print(random_params)
# prints {111: None}
print(next(iter(random_params.values())))
# prints None
```
OS: macOS Ventura 13.0.1
Python version: 3.10.8
Pytorch version: 1.13.0
**Expected behavior**
random_params should be a meaningful dictionary that I could use as params dict for a torch model

**Comment by D-X-Y** [comment]
The network parameters are contained in `full archive` files (please follow instructions at https://github.com/D-X-Y/NATS-Bench#preparation-and-download). Note that those files are pretty large.
