### ISSUE TITLE
Do arch indexes match across nasbench201 and natsbench?

### ISSUE THREAD

**Issue by debadeepta** [D-X-Y/NATS-Bench#5]
**Say I lookup a model's information by index 235 in natsbench. Is the architecture corresponding to id 235 same in earlier nasbench201 as well?**

I am comparing to some other code which is using nasbench201 api and I wanted to make sure that things were comparable. Thanks!!

**Comment by D-X-Y** [comment]
Yes, they are the same :)

**Comment by debadeepta** [comment]
Thanks!! My life is easy now :-)
