### ISSUE TITLE
What is the seed of subnet training on cifar10, 111 or 777?

### ISSUE THREAD

**Issue by xielinzhen** [D-X-Y/NATS-Bench#51]
**Describe the Question**
- Is it about the topology search space in NATS-Bench?
- yes

I use the following code to query the accuracy of the specified subnet, I then retrained the subnet with seeds 111 and 777, but couldn't get the same accuracy as the query,Could you tell me the seeds of training?

```
from nats_bench import create
from xautodl.models import CellStructure

model_str = '|nor_conv_1x1~0|+|nor_conv_3x3~0|nor_conv_1x1~1|+|skip_connect~0|none~1|nor_conv_1x1~2|'
arch = CellStructure.str2structure(model_str)
api = create(None, 'tss', fast_mode=True, verbose=False)
api.reset_time()
accuracy, _, _, total_cost = api.simulate_train_eval(
    arch, 'cifar10', hp="12"
)
print(f"accuracy {accuracy},  total_cost  {total_cost}")
```

**Comment by sorobedio** [comment]
Most values i saw were: 777, 888, and 999

**Comment by D-X-Y** [comment]
111, 777, 888, or 999. The seed is stored in the benchmark file, and should be easy to find.

However, even if you use the same seed, it may still not be able to get the exactly same accuracy given the different machine environment, and DL library version. How much difference have you seen?

**Comment by xielinzhen** [comment]
Let's say this subnet: |avg_pool_3x3~0|+|nor_conv_1x1~0|nor_conv_3x3~1|+|nor_conv_3x3~0|nor_conv_3x3~1|avg_pool_3x3~2|

This is the result of simulation training:   accuracy 64.32399999023437
![选区_027](https://user-images.githubusercontent.com/37104373/215636472-0ed7212f-8101-4de6-a19b-c2f47cfe1935.png)

This is the result of actual training using seed 111:   accuracy 73.29
![选区_026](https://user-images.githubusercontent.com/37104373/215636631-50063a4e-9952-4f54-bb23-bcb0044f0b2f.png)

**Comment by xielinzhen** [comment]
Thank you for your reply. The problem has been solved
I should have used this method to simulate training instead of the second one below
```
index = api.query_index_by_arch(arch)

info = api.get_more_info(
    index, "cifar10", iepoch=None, hp=12, is_random=True
)
print(info['test-accuracy'])
```

```
accuracy, _, _, total_cost = api.simulate_train_eval(
    arch, 'cifar10', hp="12"
)
print(f"accuracy {accuracy},  total_cost  {total_cost}")
```
