### ISSUE TITLE
Empty evaluated_indexes

### ISSUE THREAD

**Issue by zxl101** [D-X-Y/NATS-Bench#7]
**Describe the bug**
When using find_best(), got error **ValueError: invalid index : -1 vs. 15625.**. 
After checking the code, the problem seems to be self.evaluated_indexes is an empty set.
I've downloaded the benchmark file and archive and put them in $TORCH_HOME.
If I added one line of code ```api.evaluated_indexes = set(range(amount))``` to the script, the code works but the script is killed after index=14587

**To Reproduce**
Please provide a small script to reproduce the behavior:
```
from nats_bench import create

api = create(None, 'tss', fast_mode=True, verbose=True,)

best_acc = 0
best_arch = -1
amount = len(api)
# api.evaluated_indexes = set(range(amount))

index, acc = api.find_best(dataset='cifar10', metric_on_set='val')
# print(index)
# for i, arch in enumerate(api):
#     info = api.get_more_info(i, 'cifar10')
#     test_acc = info['test-accuracy']
#     if test_acc > best_acc:
#         best_acc = test_acc
#         best_arch = arch
#         print(best_arch)
```
Please let me know your OS, Python version, PyTorch version.
OS: Ubuntu 20.04.1 LTS
Python: Python 3.6.8 :: Anaconda, Inc.
PyTorch: 1.7.1+cu110

**Expected behavior**
I want to use find_best() to find the best cell structure

**Screenshots**
![Screenshot from 2021-04-08 13-16-58](https://user-images.githubusercontent.com/50291584/113963377-d4434380-986c-11eb-8f13-bbf29b768497.png)
![Screenshot from 2021-04-08 13-18-40](https://user-images.githubusercontent.com/50291584/113963460-f50b9900-986c-11eb-9146-9555f4df8030.png)

**Comment by D-X-Y** [comment]
Thanks for pointing out this issue.

It was because you created the API via fast_mode, where `evaluated_indexes` is empty at initialization and will gradually contain more architectures when querying each.

I have just updated the NATS-Bench API to fix this issue, please use the latest version (v1.3). For your convenience, I also created an example here: https://github.com/D-X-Y/NATS-Bench/blob/main/notebooks/issue-7.ipynb

Please let me know if you have any other question.

**Comment by zxl101** [comment]
Thank you for the fix. I've tried the new version and the code in the example. I've met another problem. The process is killed for some reason after running for some time.
![Screenshot from 2021-04-08 15-51-17](https://user-images.githubusercontent.com/50291584/113975049-440ff900-9882-11eb-88ed-a8dd1bb38033.png)

**Comment by D-X-Y** [comment]
That is highly possible that your machine did not have enough memory
